### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by sgehrman** [mosaicnetworks/babble#1]
--- FAIL: TestTLSTransport_CertificateValidation (0.00s)
        test_logger.go:26: time="2017-10-30T04:24:44-07:00" level=debug msg="accepted connection" from=127.0.0.1:40238 node=127.0.0.1:40237
        test_logger.go:26: time="2017-10-30T04:24:44-07:00" level=error msg="Failed to decode incoming command" error="remote error: tls: bad certificate"
        Error Trace:    tls_transport_test.go:50
        Error:          Expected nil, but got: x509.CertificateInvalidError{Cert:(*x509.Certificate)(0xc4200cd400), Reason:1}

        Error Trace:    tls_transport_test.go:51
        Error:          Expected value not to be nil.

        test_logger.go:26: time="2017-10-30T04:24:44-07:00" level=debug msg="accepted connection" from=127.0.0.1:52592 node=127.0.0.1:40871
        test_logger.go:26: time="2017-10-30T04:24:44-07:00" level=error msg="Failed to decode incoming command" error="remote error: tls: bad certificate"
        Error Trace:    tls_transport_test.go:55
        Error:          Object expected to be of type x509.UnknownAuthorityError, but was x509.CertificateInvalidError

        test_logger.go:26: time="2017-10-30T04:24:44-07:00" level=debug msg="accepted connection" from=127.0.0.1:40242 node=127.0.0.1:40237
        Error Trace:    tls_transport_test.go:60
        Error:          Object expected to be of type *net.OpError, but was x509.CertificateInvalidError

        test_logger.go:26: time="2017-10-30T04:24:44-07:00" level=error msg="Failed to decode incoming command" error="remote error: tls: bad certificate"
--- FAIL: TestTLSTransport_EnvironCert (0.11s)
        test_logger.go:26: time="2017-10-30T04:24:44-07:00" level=debug msg="accepted connection" from=127.0.0.1:56660 node=127.0.0.1:33087
        test_logger.go:26: time="2017-10-30T04:24:44-07:00" level=error msg="Failed to decode incoming command" error="remote error: tls: bad certificate"
        Error Trace:    tls_transport_test.go:77
        Error:          Expected nil, but got: x509.CertificateInvalidError{Cert:(*x509.Certificate)(0xc4203e2f00), Reason:1}

        Error Trace:    tls_transport_test.go:78
        Error:          Expected value not to be nil.

FAIL
FAIL    github.com/babbleio/babble/net  0.138s

**Comment by arrivets** [comment]
What version of Go are you using? You need at least 1.9

Actually the problem doesn't seem to have anything to do with the Go version.
Looking into it...

**Comment by sgehrman** [comment]
I have 1.9.  I had other issues too. Couldn't get it working correctly.
Window came up but didn't work. Glide also didn't find my gopath unless I
did an export in bash to redefine it before glide install. Will try again
tomorrow.

**Comment by arrivets** [comment]
Ok the certificates problem came from the fact that the test certificates had expired.
I updated the test certificates and the tests now run smoothly.

**Comment by arrivets** [comment]
I have only tested all the scripts and demos on Ubuntu 16.04.

There is extra work to do on other platforms.

I am going to try to create a docker container or a set of binaries that simplifies everything.

**Comment by sgehrman** [comment]
ok, great, I'm in ubuntu 17.10, Any idea why glide didn't see my GOPATH and DISPLAY env vars inside .bashrc?  I had to set those in bash to get them working

**Comment by arrivets** [comment]
I think when you set env vars in .bashrc you have to source that file (or open a new terminal) for the changes to take effect. 
Anyway glide is giving me a lot of headaches as well...
