### ISSUE TITLE
How to build it in windows

### ISSUE THREAD

**Issue by peacess** [mosaicnetworks/babble#108]
error: 

# github.com/mosaicnetworks/babble/src/hashgraph
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:350:19: assignment mismatch: 2 variables but 1 values
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:350:31: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:400:18: too many arguments in call to tx.Commit
	have (nil)
	want ()
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:410:13: assignment mismatch: 2 variables but 1 values
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:410:26: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:420:20: assignment mismatch: 2 variables but 1 values
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:420:38: not enough arguments in call to eventItem.Value
	have ()
	want (func([]byte) error)
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:453:13: assignment mismatch: 2 variables but 1 values
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:453:26: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:481:25: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
D:\peace\gopath\src\github.com\mosaicnetworks\babble\src\hashgraph\badger_store.go:481:25: too many errors

Compilation finished with exit code 2

**Comment by arrivets** [comment]
This looks like you have the wrong version of BadgerDB.
Sometimes glide, the dependency management tool, is a bit flaky. 
Please ensure that you have version v1.5.3 of badgerdb in the vendor folder (after running `make vendor` or `glide install` from the root directory)
