### ISSUE TITLE
Error in cloning dependencies in glide_cache while executing make dist 

### ISSUE THREAD

**Issue by Sharma-Hrishabh** [mosaicnetworks/babble#114]
https://github.com/mosaicnetworks/babble/blob/e79058d5ed3c1d2e788fc8e2bb0d231011b9966f/scripts/dist_build.sh#L24

**Comment by Sharma-Hrishabh** [comment]
Fix the error raised when pulling dependencies repositories in glide_cache

**Comment by arrivets** [comment]
What error message are you getting? Can't seem to reproduce this.

**Comment by Sharma-Hrishabh** [comment]
During make dist execution I was getting errors like this one- 

`Unable to checkout github.com/pelletier/go-toml
[ERROR]	Update failed for github.com/pelletier/go-toml: Unable to get repository: Cloning into 'glide_cache/cache/src/https-github.com-pelletier-go-toml'...
fatal: unable to access 'https://github.com/pelletier/go-toml/': Could not resolve host: github.com
: exit status 128`

And for other dependencies ,the error was same.
What worked for me is to change that directory path from glide_cache to $(pwd).I have checked on multiple machines.
I think we need to give the absolute path there.That's why pwd is working

**Comment by arrivets** [comment]
That looks more like an internet connection issue
