### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by arrivets** [mosaicnetworks/babble#118]
Make better use of Info vs Debug levels.

We want "normal" users to use the Info level, but as of today:
- Info doesn't log enough
- Debug logs too much

So put more logs that are currently in Debug, in Info.

In the process, think of new helpful log messages and remove useless ones.

**Comment by jonknight73** [comment]
As an aside to this, within the Monetd repo, the default logging is going to be changed from debug to info. It seems to better fit the intended audience.
