### ISSUE TITLE
is it possibile to port this project in java?

### ISSUE THREAD

**Issue by publicocean0** [mosaicnetworks/babble#123]
is there license problems ? what do you suggest about the best way for doing it?

**Comment by joneskm** [comment]
There are no licensing issues. I'm not sure about the best way of doing this but we've had success in using gomobile (https://godoc.org/golang.org/x/mobile/cmd/gomobile) to generate an aar which we've used in android apps. You could try extracting the jar file and jni directory from the aar then importing them into your project.
