### ISSUE TITLE
Validation of transactions

### ISSUE THREAD

**Issue by shiraShapira** [mosaicnetworks/babble#144]
I added an implementation of "Validation of transactions" via the proxy, but then I saw a serious problem-
the creator of transaction increase the index of  his events in the "known" array but then if someone doesn't approve the transaction,he doesn't insert the event and doesn't increase the index of sender in his "known" array, so it will be sent to him again and again in gossip  because of the diff in the creator index..
I need an advice how to solve this problem..
Thanks!!

**Comment by arrivets** [comment]
Have a look at this related issue #125

There is no obvious solution to what you are trying to do.

We tend to filter transactions at the application layer, not the gossip layer.
