### ISSUE TITLE
RecordHeads Function

### ISSUE THREAD

**Issue by shiraShapira** [mosaicnetworks/babble#145]
In core.go file you have recordHeads func,there is a problem there that you may send null as parameter of "other parent" to addSelfEvent func. (see image)
This fact may fill the graph with events that have just self event even though they aren't first of their creator.

![image](https://user-images.githubusercontent.com/40023506/90981483-f2706380-e569-11ea-886a-7640e5c30d34.png)

**Comment by arrivets** [comment]
Hey,

This is done on purpose. There is no problem inserting Events 
with no other-parent.

We create such Events when we want to submit new transactions
as part of a gossip push.
