### ISSUE TITLE
Is there real time chat room ?

### ISSUE THREAD

**Issue by ChainCoderX** [mosaicnetworks/babble#152]
do you have real time chat room ?

**Comment by arrivets** [comment]
Hey, do you mean a product that uses Babble or something like Slack or Telegram to just have a chat with us?
- In the first case we have this: https://github.com/mosaicnetworks/babble-android 
  A chat app for android, but we took it off the App Store
- In the latter: https://join.slack.com/t/babbleio/shared_invite/zt-3dvemboy-BipDxD1YpXVNCjEngnqpmw

**Comment by ChainCoderX** [comment]
both,
thank you.
