### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by asafyish** [mosaicnetworks/babble#2]
Hi,

Is it possible to release binaries ?
It will be easier then compiling.

**Comment by arrivets** [comment]
Hey,
That would be possible of course. However, the code is going to evolve very quickly in the next few weeks so instead of releasing binaries I was thinking of creating a Docker image to compile the code and produce artifacts for various platforms. 
This makes it a lot easier to compile without giving us the extra work of maintaining binaries for every platform.
What do you think?

**Comment by asafyish** [comment]
Since the product is open source, I think you can use a solution like https://circleci.com/ for free to do CI, and once in a while, use the 'Release' feature of github to actually attach the compiled binaries from circleci. That way you don't need to manually build, and you gain the benefit of running tests on each commit.

**Comment by arrivets** [comment]
Interesting, I'll check it out

**Comment by mdyring** [comment]
Tendermint guys are looking into https://goreleaser.com/

Unfortunately I don't know enough about Go to help, but Travis and AppVeyor (which I use for CI) has the ability to push binaries if CI succeeds.. Maybe CircleCI can do the same(?).

**Comment by asafyish** [comment]
I don't know if CircleCI can, but if it can't - it's still possible to use Travis or AppVeyor they are all free for open source projects.

I just looked on goreleaser, looks really nice, it's possible to configure the mentioned tools to use it and push binaries here.

**Comment by arrivets** [comment]
Ok,

 Now ```make dist``` will run a build inside a docker container and generate binaries for several platforms.

I also setup circleci to build and test the master branch on every push.

I have not automated the release step yet. goreleaser is very cool but I like to keep more control over the process so I basically copied and tweaked a lot of the scripts from tendermint.

The demo now pulls Docker images from our Docker Hub repos. No need to build locally anymore! All you need is docker.

Thanks for your suggestions.
Does this help?

**Comment by arrivets** [comment]
Forgot to mention that the binaries for v0.1.0 can be downloaded from the releases tab

**Comment by asafyish** [comment]
Hi,

Yes, it's really helpful to just download the latest version and tinker with it.

Thanks !
I am sure it will lower the barrier for experimenting !
