### ISSUE TITLE
Error running `make test`: Fatalf format %s has arg expectedResp.FromID of wrong type int

### ISSUE THREAD

**Issue by metalaureate** [mosaicnetworks/babble#21]
After making the latest version, should I be concerned that when I `make test`, a couple of errors are reported:

> $ make test
> glide novendor | xargs go test
> ?   	github.com/babbleio/babble/cmd/babble	[no test files]
> ?   	github.com/babbleio/babble/cmd/dummy_client	[no test files]
> ok  	github.com/babbleio/babble/common	(cached)
> ok  	github.com/babbleio/babble/crypto	(cached)
> ok  	github.com/babbleio/babble/hashgraph	(cached)
> ok  	github.com/babbleio/babble/net	(cached)
> # github.com/babbleio/babble/node
> node/node_test.go:115: Fatalf format %s has arg expectedResp.FromID of wrong type int
> node/node_test.go:454: Fatalf format %s has arg expectedResp.FromID of wrong type int
> FAIL	github.com/babbleio/babble/node [build failed]
> ok  	github.com/babbleio/babble/proxy	0.012s
> ?   	github.com/babbleio/babble/proxy/app	[no test files]
> ?   	github.com/babbleio/babble/proxy/babble	[no test files]
> ?   	github.com/babbleio/babble/service	[no test files]
> ?   	github.com/babbleio/babble/version	[no test files]
> make: *** [test] Error 1

**Comment by arrivets** [comment]
Hi, thanks for the detailed output.
I dont think you have the latest version though.

**Comment by metalaureate** [comment]
You are right. Don't know how that happened. Thanks for the quick response; sorry for the false alarm.

> ?   	github.com/babbleio/babble/cmd/babble	[no test files]
> ?   	github.com/babbleio/babble/cmd/dummy_client	[no test files]
> ok  	github.com/babbleio/babble/common	(cached)
> ok  	github.com/babbleio/babble/crypto	(cached)
> ok  	github.com/babbleio/babble/hashgraph	(cached)
> ok  	github.com/babbleio/babble/net	(cached)
> ok  	github.com/babbleio/babble/node	6.321s
> ok  	github.com/babbleio/babble/proxy	0.014s
> ?   	github.com/babbleio/babble/proxy/app	[no test files]
> ?   	github.com/babbleio/babble/proxy/babble	[no test files]
> ?   	github.com/babbleio/babble/service	[no test files]
> ?   	github.com/babbleio/babble/version	[no test files]
