### ISSUE TITLE
Does this project infringe on hashgraph patents

### ISSUE THREAD

**Issue by Serkan-devel** [mosaicnetworks/babble#26]
I'm sure this project should resemble hashgraph in an open source manner, but open source doesn't save from patent issues but I still want to see this project here succeed

**Comment by Serkan-devel** [comment]
How is it in europe for example?

**Comment by arrivets** [comment]
Patents are territorial by nature. US patents only give the holder rights in the US, and rights to stop others from importing the patented products into the US.
As far as I know, Swirlds only has patents in the US.

**Comment by arrivets** [comment]
It is not impossible but I think it is very unlikely. 
It would have to be approved by each country separately.
Algorithms are not patentable in most European countries.

**Comment by Serkan-devel** [comment]
I think Richard Stallman fought for that
