### ISSUE TITLE
Exception when running 0.1.0 binaries

### ISSUE THREAD

**Issue by asafyish** [mosaicnetworks/babble#3]
Hi,

I tried running "babble_0.1.0_darwin_amd64" and an exception:
```
DEBU[0000] RUN                                           cache_size=500 client_addr="127.0.0.1:1339" datadir="/Users/ayishai/Library/BABBLE" heartbeat=1000 max_pool=2 no_client=false node_addr="127.0.0.1:1337" proxy_addr="127.0.0.1:1338" service_addr="127.0.0.1:80" tcp_timeout=1000
DEBU[0000] Init Node                                     node="127.0.0.1:1337" peers=[]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1362201]

goroutine 1 [running]:
github.com/babbleio/babble/node.(*Core).PubKey(0xc420168280, 0xc420178000, 0xc4201212f8, 0x1091912)
	/go/src/github.com/babbleio/babble/node/core.go:67 +0x61
github.com/babbleio/babble/node.(*Core).Init(0xc420168280, 0xc420121628, 0x1)
	/go/src/github.com/babbleio/babble/node/core.go:83 +0x43
github.com/babbleio/babble/node.(*Node).Init(0xc420180000, 0x0, 0x0)
	/go/src/github.com/babbleio/babble/node/node.go:98 +0x280
main.run(0xc420168140, 0x0, 0xc420168140)
	/go/src/github.com/babbleio/babble/cmd/babble/main.go:205 +0xea6
github.com/babbleio/babble/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x13efae0, 0x149f6d8, 0xc420168140, 0xc420166000, 0x0)
	/go/src/github.com/babbleio/babble/vendor/gopkg.in/urfave/cli.v1/app.go:485 +0xd2
github.com/babbleio/babble/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x1480a8f, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1483e83, 0x8, 0x0, ...)
	/go/src/github.com/babbleio/babble/vendor/gopkg.in/urfave/cli.v1/command.go:193 +0xa99
github.com/babbleio/babble/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4201581a0, 0xc42000a060, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/babbleio/babble/vendor/gopkg.in/urfave/cli.v1/app.go:250 +0x758
main.main()
	/go/src/github.com/babbleio/babble/cmd/babble/main.go:122 +0x557
```

**Comment by arrivets** [comment]
It looks like this particular error is related to a missing key. 
Did you put a priv_key.pem file in datadir (/Users/ayishai/Library/BABBLE)?

I also notice that you are running a single node (peers[] is empty). That wont work.
You will need to run at least two nodes.

I understand this is quite painful to setup. Perhaps looking at the scripts in the demo folder could be useful.

The easiest way to generate the configuration for 2 nodes is to go into the demo/ directory and run:
```make conf nodes=2```. This will create two folders: demo/conf/node1 and demo/conf/node2.
You can change the peers.json file to use whichever IPs you want to give to your nodes. Then copy the content of the folders in the datadir of the respective nodes.

If you are not going to use docker you are going to have to be careful in setting the address flags when running both nodes otherwise there will be port conflicts..

I hope this makes sense

**Comment by asafyish** [comment]
Hi,

No I didn't created priv_key.pem - but I would expected that a proper error message will be thrown.
Right now, there aren't too many users of babble, but when you will have a bigger userbase, babble will have to tell the user (as much as possible), "User, you did X wrong. please fix", otherwise there is going to be a flood of tickets like this.

In addition, I was following the documentation, but were using the binary files, so didn't do run any 'make' commands, maybe there should be different usage instructions for binaries ?

The /Users/ayishai/Library/BABBLE folder feels like the wrong place to put configuration, I am used to having this kind of configuration under /Users/ayishai/.{folder} - /Users/ayishai/.babble, most command line tools put their configuration in a hidden folder inside the user folder (.ssh, .bash_history, .cocoapods, .electron, .npm, .vscode - just a few examples).

One last thing, the 'service_addr' is 127.0.0.1:80, which is not going to work out of the box on linux/osx, since non-root users can only use ports above 1024, so it might be better pick some other port, about 1024 (but not 8080 or 3000 - those ports are usually used by other services, and we want to minimize conflicts), even though multiple instances on the same machine WILL conflict.

Not trying to be offensive, I just think this kind of tech is really interesting and I want to see it growing in popularity !

It's working now, closing ticket.

**Comment by arrivets** [comment]
I actually value this feedback a lot. So thanks for taking the time to write this up!

I think the latest commits address the issues you mentioned above. Also I have updated the
documentation to explain the [manual setup](http://babbleio.readthedocs.io/en/latest/usage.html#manual-setup). 

There are obviously many improvements to add to the code to make it easier to adopt and more
robust. Feel free to create some pull requests for the code or the documentation :)
