### ISSUE TITLE
BFT offers less security than PoW or PoS

### ISSUE THREAD

**Issue by HarryR** [mosaicnetworks/babble#32]
With PoW a >50% majority is required to determine what truth is, whereas with BFT a 33% consensus is required.

If you add dynamic ad-hoc peers together, with no proof of work or stake, with a 33% consensus, the concept of consensus completely disappears, there is no point, there is no security, I can pwn the frack out of your 'consensus' by running a handful of commands with '&' at the end on a laptop in a hotel.

How do you propose that Babble overcomes this?

TL;DR your BFT algorithm isn't actually BFT. You misunderstand security.

BFT doesn't scale, it only works with PoA, and even then - PoS offers better security - game theoretically secure. But, you want to solve the staking problem rite? That's a difficult one, unless you can rely on the security of others to ensure immutability - but then you're just an ad-hoc para-chain (which is still really cool technology IMO).

I liked the demo though, it's just a shame the technology is fundamentally flawed.

If you can work out how to anchor ad-hoc para-chains to something more trust-worthy without having to do the whole ad-hoc security thing yourself (which is insolvable BTW) then you'll be a wise man.

**Comment by arrivets** [comment]
> If you add dynamic ad-hoc peers together, with no proof of work or stake, with a 33% consensus, the concept of consensus completely disappears, there is no point, there is no security, I can pwn the frack out of your 'consensus' by running a handful of commands with '&' at the end on a laptop in a hotel.

It is a permissioned system. To join a Babble network you need to be 'voted in' by all the other participants.
And this 'voted in' procedure can be as stringent as you want. It is implemented at the application layer. So for instance, you wouldn't be able to run any commands in my network if I didn't accept you as a participant.   

Of course you need some kind of incentive/discouragement for participants to behave correctly, even once they are in. The blockchain offers support for any Proof of Accountability type of system. 'We know who you are, we have proof that you tried to cheat, here is how we can punish you'. PoS is only one example of such a scheme.. there can be many more depending on the application.

>BFT doesn't scale, it only works with PoA, and even then - PoS offers better security - game theoretically secure. But, you want to solve the staking problem rite? That's a difficult one, unless you can rely on the security of others to ensure immutability - but then you're just an ad-hoc para-chain (which is still really cool technology IMO).

Noone is saying that BFT needs to scale.. that's the whole point of our project. Have many small ad hoc blockchains rather than one massive blockchain...

**Comment by HarryR** [comment]
(I come across very negatively sometimes btw)

Lets say I want to play poker with a small group of friends, we all agree on the participants then deposit our ETH (or other token) into a contract on the mainnet.

Then we form an ad-hoc group using Babble, do the poker playing, money shifts around, people win / lose etc. then each person takes the result back to mainnet to settle.

How would that work with babble?

**Comment by arrivets** [comment]
There are many ways it could happen.

From your example it seems that you are assuming that there is some kind of escrow contract that requires some kind of proof to distribute the funds back to the players, in proportion to their winnings.

First of all, let me point out that this is completely optional. You could just settle manually at the end of the game. 

But one way you could implement the above, is to register on the mainnet a light-client for you poker Babble network. This light client knows how to verify Babble transactions/blocks, but is also specific to your poker app.

So you would package up a proof  that you poker application is in a certain state at the end of the game.
This proof would contain something like this:
- merkle proof that the players's accounts have a certain balance. The merkle root being the application's state hash
- A block containing that state hash and signatures from  >1/3 of participants. (here you could even require more signatures.. up to you)

Then you package the proof in a format that can be interpreted by your light-client. Based on the state of the poker app, the light-client releases the escrowed funds accordingly.

All we will provide with Babble is a template for a SmartContract that verifies Babble blocks.. a light-client devoid of any application-specific logic. The rest is up to the app developers.

**Comment by HarryR** [comment]
I like the idea of proving the state of an ad-hoc Babble group, especially on Ethereum or NEO. However that would require the signatures to be ECDSA over SECP256k1 (ETH) and 256r1 (NEO).

> First of all, let me point out that this is completely optional. You could just settle manually at the end of the game.

Then what is the point of using a blockchain?

Anyway, there's another problem: a smart contract would have to be created for each game, because if multiple groups use the same contract one group could collude to steal the other groups deposits etc.

Secondly, I'm uneasy about it being a simple threshold of signatures, because any single challenger to their 'proof' needs to be able to use that same proof to intractably prove to the honest verifier (smart contract) that they didn't follow the logic of whatever's being executed within the Babble group - and I'm not sure that's doable without it being highly specific to whatever the use case is (so, it wouldn't be general purpose, or... it could be but it'd be a massive pain).

**Comment by arrivets** [comment]
> Then what is the point of using a blockchain?

The ad-hoc blockchain enables players to play without a central server. Babble is middleware to create p2p apps. Might as well make it as fault-tolerant as possible. BFT+Blockchain is the state of the art when it comes to distributed consensus. Membership protocols, incentives/discouragement, settlement mechanisms, and cross-chain communication are to be implemented on another layer.

**Comment by Serkan-devel** [comment]
> Have many small ad hoc blockchains rather than one massive blockchain...

Then how do users from two different blockchains communicate with each other?

**Comment by arrivets** [comment]
> Then how do users from two different blockchains communicate with each other?

Prove on one chain that a transaction happened on another chain.
How you package the proof defines an Inter-Blockchain Communication protocol.
How you get the proof across is open.

**Comment by Serkan-devel** [comment]
@arrivets would this work with babble https://interledger.org/ ?

**Comment by HarryR** [comment]
i think using blockchain as a main distinction confuses expectations, whereas as p2p middleware layer with fault tolerance and cryptography there are less questions about why doesnt it do X or Y.

interledger needs way more than babble to be workable, youd have to go and build what people normally think of as a blockchain to be used as a long-term store of value ontop.
