### ISSUE TITLE
Getting test to pass x509.UnknownAuthorityError

### ISSUE THREAD

**Issue by calvinchengx** [mosaicnetworks/babble#6]
```
--- FAIL: TestTLSTransport_EnvironCert (0.09s)
	test_logger.go:26: time="2017-12-01T11:12:18+08:00" level=debug msg="accepted connection" from="127.0.0.1:53266" node="127.0.0.1:53264"
        Error Trace:    tls_transport_test.go:77
	Error:		Expected nil, but got: x509.UnknownAuthorityError{Cert:(*x509.Certificate)(0xc420572000), hintErr:error(nil), hintCert:(*x509.Certificate)(nil)}

	test_logger.go:26: time="2017-12-01T11:12:18+08:00" level=error msg="Failed to decode incoming command" error="remote error: tls: bad certificate"
        Error Trace:    tls_transport_test.go:78
	Error:		Expected value not to be nil.

FAIL
```

As advised by @arrivets I tried running

```
cd config
./rootca
./testca
```

before running the tests with `make test` again but I am still getting the same error.

Is there any other steps I am missing when running my tests so that `TestTLSTransport_EnvironCert` passes?

**Comment by arrivets** [comment]
What version of go are you running?

This test uses a feature of go 1.9 (https://golang.org/pkg/crypto/x509/) that uses the environment variable SSL_CERT_FILE to point to trusted root CA certificates.

**Comment by calvinchengx** [comment]
1.9.2

**Comment by arrivets** [comment]
Ok. 
I still think it has something to do with loading the system CA pool.
They talk about it in this issue https://github.com/golang/go/issues/14311
I can't reproduce this from my machine. Working on getting OSX VM..

**Comment by calvinchengx** [comment]
This should work bd45bc3010b5824d276428cdd848ca2d521dc0f8

Part of the entire pull request. Everything seems to work now except for the stats not showing up on MacOS (i.e. `watch.sh` does not render any stats).

Everything else works, including the simple chat demo.

**Comment by arrivets** [comment]
Sure it works but it is not the same test anymore.

The idea is to test loading CAs from the system if a CA pool is not explicitly provided.

**Comment by arrivets** [comment]
could you please try replacing 

err := os.Setenv("SSL_CERT_FILE", filepath.Join(test.testdata, "ca.crt"))

with 

err := os.Setenv("SSL_CERT_DIR", test.testdata)

and not providing a pool to the tls transport?

**Comment by calvinchengx** [comment]
Tested with `err := os.Setenv("SSL_CERT_DIR", test.testdata)`. 

It still gives `x509.UnknownAuthorityError`.

I see your point about testing loading CAs from the system if a CA pool is not explicitly provided. I wonder why it doesn't know how to load the environment variable when executing on macOS.

**Comment by arrivets** [comment]
damn..

regarding the watch script, maybe try using gawk instead of awk

**Comment by calvinchengx** [comment]
Yes, I am using `gawk`.  

`brew install gawk --with-default-names` will set my terminal to use the gnu version of such coreutils program by default

**Comment by arrivets** [comment]
what happens if you remove the `tr` and `awk` statements in the watch script.. just leave `curl`?

**Comment by calvinchengx** [comment]
curl doesn't return anything at all. 

So it is most likely a macOS docker IP/port mapping difference (in comparison with how ubuntu does IP/port mapping).

Reference - https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds

```
Per-container IP addressing is not possible
The docker (Linux) bridge network is not reachable from the macOS host.
```

**Comment by calvinchengx** [comment]
Reviewing https://github.com/golang/go/blob/release-branch.go1.9/src/crypto/x509/root_unix.go#L42, `x509.SystemCertPool()` should be getting the `SSL_CERT_FILE` environment variable so I have no clue why it will fail to load the correct certs.

**Comment by arrivets** [comment]
The thing is that we are not even using the TLS transport yet.
I am tempted to move tls_transport and corresponding test to a separate branch for now
We will write better tests when the time comes to actually use TLS

**Comment by arrivets** [comment]
Interesting article about limitations of docker with macOS.. I had no idea.
We could create an extra container just to launch the watch script.
