### ISSUE TITLE
docker for macOS

### ISSUE THREAD

**Issue by calvinchengx** [mosaicnetworks/babble#7]
To monitor stats when running the docker test net on macOS, we need a workaround.  I can work on this when I have more time.

Possible workaround - https://github.com/wojas/docker-mac-network

**Comment by arrivets** [comment]
I think the best is to create a separate docker container in the same virtual network as the others and run the watch script inside it

**Comment by calvinchengx** [comment]
Right. That makes sense. Will do that instead.

---
www.calvinx.com
