### ISSUE TITLE
The presence of `develop` branch is misleading

### ISSUE THREAD

**Issue by jserv** [mosaicnetworks/babble#85]
So far, branch `develop` is behind several commits than `master` branch or even other feature branches. Will branch `develop` be taken as it implies still?

**Comment by arrivets** [comment]
Good point. 
The develop branch is supposed to be the converging branch for ongoing work. However, we still want to keep it relatively stable. We are in the middle of a major task, dynamic participants, and we find ourselves making big changes to important sections of the code on a regular basis. The situation should stabilise once we get closer to a final solution for dynamic participants; possibly in January/February. The most up-to-date branche is join_request if you are interested.
